In [3]:
###Consider the below code to answer further questions:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1: Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Ans: Yes, there is a difference in the data type of list_ and array_list.

list_ is a Python list, and its elements are strings ('1', '2', '3', '4', '5'), while array_list is a NumPy array, and its elements are also strings.

The data type of list_ is list, while the data type of array_list is numpy.ndarray

We can verify it as:

In [7]:
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [9]:
list(map(lambda x: type(x), list_))

[str, str, str, str, str]

In [10]:
list(map(lambda x: type(x), array_list))

[numpy.str_, numpy.str_, numpy.str_, numpy.str_, numpy.str_]

Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [11]:
array_list = np.array(object = list_, dtype = int)

In [12]:
list(map(lambda x: type(x), array_list))

[numpy.int64, numpy.int64, numpy.int64, numpy.int64, numpy.int64]

Yes, By doing array_list = np.array(object = list_, dtype = int) we're specifying the data type of the elements in a NumPy array to be int. It creates a NumPy array with elements of the int data type.

In [ ]:
Consider the below code to answer further questions:

In [13]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable num_array:
1.shape                 2.size

In [17]:
print('1. Shape :', num_array.shape)
print('2. Size :', num_array.size)

1. Shape : (2, 3)
2. Size : 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

Hint: The size of the array will be 9 and the shape will be (3,3).

In [18]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr.size, arr.shape

(9, (3, 3))

Q6. Create an identity matrix of shape (5,5) using numpy functions?

Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.

In [20]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])