In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,(3,4))

In [3]:
arr

array([[3, 2, 9, 9],
       [3, 3, 2, 7],
       [4, 5, 8, 1]])

In [4]:
arr.reshape(6,2)

array([[3, 2],
       [9, 9],
       [3, 3],
       [2, 7],
       [4, 5],
       [8, 1]])

In [5]:
arr.reshape(2,6)

array([[3, 2, 9, 9, 3, 3],
       [2, 7, 4, 5, 8, 1]])

In [6]:
arr

array([[3, 2, 9, 9],
       [3, 3, 2, 7],
       [4, 5, 8, 1]])

In [7]:
arr.T

array([[3, 3, 4],
       [2, 3, 5],
       [9, 2, 8],
       [9, 7, 1]])

In [8]:
arr.flatten()

array([3, 2, 9, 9, 3, 3, 2, 7, 4, 5, 8, 1])

In [9]:
arr1=np.array([1,2,3,4,5])

In [10]:
arr1

array([1, 2, 3, 4, 5])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [14]:
arr

array([[3, 2, 9, 9],
       [3, 3, 2, 7],
       [4, 5, 8, 1]])

In [15]:
np.squeeze(arr)

array([[3, 2, 9, 9],
       [3, 3, 2, 7],
       [4, 5, 8, 1]])

In [17]:
data=np.array([[1],[2],[3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data)

array([1, 2, 3])

In [20]:
arr1

array([1, 2, 3, 4, 5])

In [22]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [24]:
np.roll(arr1,2)

array([4, 5, 1, 2, 3])

In [26]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [28]:
##binary

In [29]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [30]:
arr1

array([[4, 7, 9, 1],
       [3, 5, 6, 9],
       [1, 9, 7, 9]])

In [31]:
arr2

array([[8, 6, 3, 4],
       [3, 8, 7, 2],
       [2, 3, 7, 3]])

In [32]:
arr1+arr2

array([[12, 13, 12,  5],
       [ 6, 13, 13, 11],
       [ 3, 12, 14, 12]])

In [33]:
arr1*arr2

array([[32, 42, 27,  4],
       [ 9, 40, 42, 18],
       [ 2, 27, 49, 27]])

In [34]:
arr1-arr2

array([[-4,  1,  6, -3],
       [ 0, -3, -1,  7],
       [-1,  6,  0,  6]])

In [35]:
arr1/arr2

array([[0.5       , 1.16666667, 3.        , 0.25      ],
       [1.        , 0.625     , 0.85714286, 4.5       ],
       [0.5       , 3.        , 1.        , 3.        ]])

In [37]:
arr1%arr2

array([[4, 1, 0, 1],
       [0, 5, 6, 1],
       [1, 0, 0, 0]])

In [38]:
arr1**arr2

array([[ 65536, 117649,    729,      1],
       [    27, 390625, 279936,     81],
       [     1,    729, 823543,    729]])

In [40]:
arr1&arr2

array([[0, 6, 1, 0],
       [3, 0, 6, 0],
       [0, 1, 7, 1]])

In [41]:
~arr1

array([[ -5,  -8, -10,  -2],
       [ -4,  -6,  -7, -10],
       [ -2, -10,  -8, -10]])

In [42]:
arr1|arr2

array([[12,  7, 11,  5],
       [ 3, 13,  7, 11],
       [ 3, 11,  7, 11]])

In [43]:
arr1>arr2

array([[False,  True,  True, False],
       [False, False, False,  True],
       [False,  True, False,  True]])

In [44]:
#NUMPY STRING

In [46]:
arr=np.array(['sunita','deswal'])

In [47]:
np.char.upper(arr)

array(['SUNITA', 'DESWAL'], dtype='<U6')

In [48]:
np.char.title(arr)

array(['Sunita', 'Deswal'], dtype='<U6')

In [49]:
np.char.capitalize(arr)

array(['Sunita', 'Deswal'], dtype='<U6')

In [50]:
###numpy mathamatical

In [51]:
arr1

array([[4, 7, 9, 1],
       [3, 5, 6, 9],
       [1, 9, 7, 9]])

In [52]:
np.sin(arr1)

array([[-0.7568025 ,  0.6569866 ,  0.41211849,  0.84147098],
       [ 0.14112001, -0.95892427, -0.2794155 ,  0.41211849],
       [ 0.84147098,  0.41211849,  0.6569866 ,  0.41211849]])

In [53]:
np.cos(arr1)

array([[-0.65364362,  0.75390225, -0.91113026,  0.54030231],
       [-0.9899925 ,  0.28366219,  0.96017029, -0.91113026],
       [ 0.54030231, -0.91113026,  0.75390225, -0.91113026]])

In [54]:
np.tan(arr1)

array([[ 1.15782128,  0.87144798, -0.45231566,  1.55740772],
       [-0.14254654, -3.38051501, -0.29100619, -0.45231566],
       [ 1.55740772, -0.45231566,  0.87144798, -0.45231566]])

In [55]:
np.tanh(arr1)

array([[0.9993293 , 0.99999834, 0.99999997, 0.76159416],
       [0.99505475, 0.9999092 , 0.99998771, 0.99999997],
       [0.76159416, 0.99999997, 0.99999834, 0.99999997]])

In [56]:
np.log10(arr1)

array([[0.60205999, 0.84509804, 0.95424251, 0.        ],
       [0.47712125, 0.69897   , 0.77815125, 0.95424251],
       [0.        , 0.95424251, 0.84509804, 0.95424251]])

In [57]:
np.exp(arr1)

array([[5.45981500e+01, 1.09663316e+03, 8.10308393e+03, 2.71828183e+00],
       [2.00855369e+01, 1.48413159e+02, 4.03428793e+02, 8.10308393e+03],
       [2.71828183e+00, 8.10308393e+03, 1.09663316e+03, 8.10308393e+03]])

In [58]:
np.sqrt(arr1)

array([[2.        , 2.64575131, 3.        , 1.        ],
       [1.73205081, 2.23606798, 2.44948974, 3.        ],
       [1.        , 3.        , 2.64575131, 3.        ]])

In [60]:
np.power(arr1,2)

array([[16, 49, 81,  1],
       [ 9, 25, 36, 81],
       [ 1, 81, 49, 81]])

In [61]:
np.mean(arr1)

5.833333333333333

In [63]:
np.median(arr1)

6.5

In [64]:
np.std(arr1)

2.9107081994288304

In [65]:
np.var(arr1)

8.472222222222223

In [67]:
np.min(arr1)

1

In [68]:
np.max(arr1)

9

In [70]:
###Sort search & Counting 

In [71]:
arr=np.array([1,2,3,44,556,776,877,654,])

In [72]:
arr

array([  1,   2,   3,  44, 556, 776, 877, 654])

In [74]:
np.sort(arr)

array([  1,   2,   3,  44, 556, 654, 776, 877])

In [75]:
np.searchsorted(arr,34)

3

In [76]:
arr1=np.array([0,23,566,0,0,0,0,0,0])

In [77]:
np.count_nonzero(arr1)

2

In [78]:
arr

array([  1,   2,   3,  44, 556, 776, 877, 654])

In [79]:
np.where(arr>44)

(array([4, 5, 6, 7]),)

In [80]:
np.extract(arr>4,arr)

array([ 44, 556, 776, 877, 654])

In [81]:
### numpy Byte swapping

In [82]:
arr

array([  1,   2,   3,  44, 556, 776, 877, 654])

In [84]:
arr.byteswap()

array([   72057594037927936,   144115188075855872,   216172782113783808,
        3170534137668829184,  3171097087622250496,   577305177233555456,
        7855122175064276992, -8214002770370363392])

In [85]:
#numpy copies

In [86]:
arr

array([  1,   2,   3,  44, 556, 776, 877, 654])

In [87]:
a=np.copy(arr)

In [88]:
a

array([  1,   2,   3,  44, 556, 776, 877, 654])

In [89]:
b=arr.view()

In [90]:
b

array([  1,   2,   3,  44, 556, 776, 877, 654])

In [91]:
b[0]=67

In [92]:
b

array([ 67,   2,   3,  44, 556, 776, 877, 654])

In [93]:
arr

array([ 67,   2,   3,  44, 556, 776, 877, 654])

In [94]:
##numpy matrix

In [96]:
import numpy.matlib as nm

In [97]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [99]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [101]:
##numpy linear


In [102]:
arr1=np.random.randint([[2,5],[4,5]])
arr2=np.random.randint([[3,9],[4,5]])

In [103]:
np.dot(arr1,arr2)

array([[0, 0],
       [0, 3]])

In [104]:
arr1@arr2

array([[0, 0],
       [0, 3]])