In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[2,4]])

array([[1, 2],
       [2, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
a=[1,2,3,4]

In [11]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [12]:
b=np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [15]:
a=np.array(l)

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c=a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
c[0]

1

In [20]:
c[0]=100

In [21]:
c

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
d=np.copy(a)

In [24]:
d

array([100,   2,   3,   4])

In [25]:
a[1]=400

In [26]:
a

array([100, 400,   3,   4])

In [27]:
d

array([100,   2,   3,   4])

In [29]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
iterable=(i*i for i in range(5))

In [36]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [42]:
np.fromstring('234 234' , sep = ' ')

array([234., 234.])

In [43]:
np.fromstring('4,5' , sep = ' ,')

array([4., 5.])

In [44]:
###numpy= data type

In [45]:
l=[2,3,4,5,7]

In [46]:
l

[2, 3, 4, 5, 7]

In [47]:
ar=np.array(l)

In [48]:
ar

array([2, 3, 4, 5, 7])

In [49]:
ar.ndim

1

In [50]:
ar2=np.array([[2,3,4],[5,6,7]])

In [51]:
ar2

array([[2, 3, 4],
       [5, 6, 7]])

In [52]:
ar2.ndim

2

In [53]:
ar.size

5

In [54]:
ar2.size

6

In [55]:
ar.shape

(5,)

In [56]:
ar2.shape

(2, 3)

In [57]:
ar.dtype

dtype('int64')

In [58]:
ar2.dtype

dtype('int64')

In [59]:
ar22=np.array([(2,3,4),(33,22.3,45)])

In [60]:
ar22

array([[ 2. ,  3. ,  4. ],
       [33. , 22.3, 45. ]])

In [61]:
ar22.dtype

dtype('float64')

In [62]:
range(5)

range(0, 5)

In [63]:
list(range(5))

[0, 1, 2, 3, 4]

In [64]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [65]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [66]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [67]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [68]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [74]:
ar4=np.zeros((3,4,2,3))

In [75]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [76]:
ar4.ndim

4

In [77]:
np.ones(4)

array([1., 1., 1., 1.])

In [78]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
on=np.ones((2,3,2))

In [82]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [83]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [85]:
np.empty((3,5))

array([[4.64019639e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [86]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [88]:
np.logspace(2,3,10)

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

In [89]:
np.logspace(2,3,10,base=2)

array([4.        , 4.32023896, 4.66611616, 5.0396842 , 5.44316   ,
       5.87893797, 6.34960421, 6.85795186, 7.4069977 , 8.        ])

In [92]:
arr=np.random.randn(3,4)

In [93]:
import pandas as pd

In [94]:
pd.DataFrame(arr)

0         1         2         3
0  0.122827 -1.894567  0.200723  0.101141
1  0.206758  0.047167 -1.447151  1.890320
2  0.517102 -1.615060  1.441329 -0.789399

In [96]:
np.random.randn(3,4)

array([[-0.17203037, -1.85958842, -0.68765797, -0.05881459],
       [ 1.76385587,  1.02747702, -0.0392602 ,  1.11163895],
       [ 0.45920416,  0.43988985, -0.74275291, -0.35578055]])

In [97]:
np.random.randint(1,110,(3,4))

array([[ 33,  99,  34,  27],
       [  6, 108,  96,  55],
       [ 76,  95,  27,  45]])

In [103]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv("test.csv")

In [104]:
arr=np.random.rand(3,4)

In [105]:
arr

array([[0.11494448, 0.31657307, 0.80919042, 0.61193037],
       [0.42165752, 0.28102801, 0.80874784, 0.98044268],
       [0.49790443, 0.19586593, 0.3478713 , 0.86017713]])

In [107]:
arr1=arr.reshape(6,2)

In [108]:
arr1

array([[0.11494448, 0.31657307],
       [0.80919042, 0.61193037],
       [0.42165752, 0.28102801],
       [0.80874784, 0.98044268],
       [0.49790443, 0.19586593],
       [0.3478713 , 0.86017713]])

In [109]:
arr1[1]

array([0.80919042, 0.61193037])

In [111]:
arr1[1][1]

0.6119303722517277

In [112]:
arr1[2:5]

array([[0.42165752, 0.28102801],
       [0.80874784, 0.98044268],
       [0.49790443, 0.19586593]])

In [113]:
arr1[2:5,1]

array([0.28102801, 0.98044268, 0.19586593])

In [114]:
arr1[1,1]

0.6119303722517277

In [118]:
arr=np.random.randint(1,100,(5,5))

In [119]:
arr

array([[66, 63, 48, 50, 93],
       [99, 96, 66, 22, 96],
       [20, 85, 66, 99, 82],
       [48,  5, 33, 15, 61],
       [ 1, 20, 10, 14, 50]])

In [124]:
arr[arr>50]

array([66, 63, 93, 99, 96, 66, 96, 85, 66, 99, 82, 61])

In [125]:
arr

array([[66, 63, 48, 50, 93],
       [99, 96, 66, 22, 96],
       [20, 85, 66, 99, 82],
       [48,  5, 33, 15, 61],
       [ 1, 20, 10, 14, 50]])

In [127]:
arr[2:4,[1,2]]

array([[85, 66],
       [ 5, 33]])

In [129]:
arr[0][0]=500

In [130]:
arr

array([[500,  63,  48,  50,  93],
       [ 99,  96,  66,  22,  96],
       [ 20,  85,  66,  99,  82],
       [ 48,   5,  33,  15,  61],
       [  1,  20,  10,  14,  50]])

In [133]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [134]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 1]])

In [135]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [136]:
arr1+arr2

array([[3, 3, 4],
       [3, 2, 3],
       [2, 2, 2]])

In [137]:
arr1-arr2

array([[-1, -1,  0],
       [-1,  0,  1],
       [ 0,  0,  0]])

In [138]:
arr1*arr2

array([[2, 2, 4],
       [2, 1, 2],
       [1, 1, 1]])

In [139]:
arr1/arr2

array([[0.5, 0.5, 1. ],
       [0.5, 1. , 2. ],
       [1. , 1. , 1. ]])

In [140]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 1]])

In [141]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [142]:
arr1@arr2

array([[6, 5, 5],
       [6, 5, 5],
       [5, 4, 4]])

In [143]:
arr1/0

/tmp/ipykernel_2692/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [144]:
arr1+100

array([[101, 101, 102],
       [101, 101, 102],
       [101, 101, 101]])

In [145]:
arr1**2

array([[1, 1, 4],
       [1, 1, 4],
       [1, 1, 1]])

In [146]:
#numpt Broadcasting

In [147]:
arr=np.zeros((4,4))

In [148]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [149]:
row =np.array([1,2,3,4])

In [150]:
row

array([1, 2, 3, 4])

In [151]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [153]:
row.T

array([1, 2, 3, 4])

In [154]:
col=np.array([[1,2,3,4]])

In [155]:
col

array([[1, 2, 3, 4]])

In [156]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [157]:
col.T +arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [158]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [160]:
arr1=np.random.randint(1,4,(3,4))

In [161]:
arr1

array([[2, 1, 2, 1],
       [3, 1, 1, 2],
       [1, 1, 2, 1]])

In [162]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356, 1.        ],
       [1.73205081, 1.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.41421356, 1.        ]])

In [163]:
np.exp(arr1)

array([[ 7.3890561 ,  2.71828183,  7.3890561 ,  2.71828183],
       [20.08553692,  2.71828183,  2.71828183,  7.3890561 ],
       [ 2.71828183,  2.71828183,  7.3890561 ,  2.71828183]])

In [164]:
np.log10(arr1)

array([[0.30103   , 0.        , 0.30103   , 0.        ],
       [0.47712125, 0.        , 0.        , 0.30103   ],
       [0.        , 0.        , 0.30103   , 0.        ]])

In [165]:
np.mean(arr1)

1.5